#!/usr/bin/env bash

main() {
  old_="lucky_starter_template"
  new_="$1"

  sed -i "s/$old_/$new_/g" _README.md
  sed -i "s/$old_/$new_/g" config/cookies.cr
  sed -i "s/$old_/$new_/g" config/database.cr
  sed -i "s/$old_/$new_/g" shard.yml
  mv "src/$old_.cr" "src/$new_.cr"
  rm README.md
  mv _README.md README.md

  echo "Please run:"
  echo '$ rm setup'
  echo '$ git add .'
  echo '$ git commit -m "Initial commit (from template)"'
}

main "$@"
